### ISSUE TITLE
"Search here" button has no text

### ISSUE THREAD

**Issue by lanzwerk** [fplacardona/LocalMusicDiscovery#2]
if not pressed label text on search here button is white on white
<img width="414" alt="screenshot 2017-02-06 11 13 32" src="https://cloud.githubusercontent.com/assets/16734260/22643089/64842c54-ec5d-11e6-9d9a-f52b35d0a5ff.png">

firefox, macOS

**Comment by GuilleVENT** [comment]
Ferran still has to make it all "prety looking"
I just wanted to make it functional

Did you manage to fix the problem with "new york" ?

**Comment by lanzwerk** [comment]
nope, but something is off with the artists anyway. i get too many artists for my location that are unrelated to it.

**Comment by fplacardona** [comment]
Fixed on the latest commit -  Design and style updated. Deleted the Spotify Follow button due to mismatch with overall design.
