### ISSUE TITLE
Artist search if off

### ISSUE THREAD

**Issue by lanzwerk** [fplacardona/LocalMusicDiscovery#3]
"New York" does not return artists from New York

too many artists returned for a given location

**Comment by GuilleVENT** [comment]
Too many artists? In the case of a city with 2 words ? Or always? 

If i'm not mistaken when given for example "seattle" it returns as many artists as when its working with the location

**Comment by GuilleVENT** [comment]
I think the problem when giving for example "new york" is that he looks for artist located in "new" and then artist that are called "york" and that is what is given later to the getID function

**Comment by GuilleVENT** [comment]
it also may be because of the text input. maybe it's not given as a string... idk but that may be a possibility.
try giving "new york" in the first draft of the program that you had a couple of weeks ago and see what comes out there. it may not be a problem of musicbrainz.

**Comment by lanzwerk** [comment]
location search returns proper results
