### ISSUE TITLE
change button colors

### ISSUE THREAD

**Issue by lanzwerk** [fplacardona/LocalMusicDiscovery#5]
the button "change song" would benefit from having inverted colors from the beginning, not only on mouseover. this would make it more recognizable as an object to interact with.
<img width="164" alt="screenshot 2017-02-07 02 17 07" src="https://cloud.githubusercontent.com/assets/16734260/22673642/ac04c7ae-ecdb-11e6-8c8d-45609dc94a86.png">

**Comment by fplacardona** [comment]
Fixed in the latest commit!
