### ISSUE TITLE
limit search bar width

### ISSUE THREAD

**Issue by lanzwerk** [fplacardona/LocalMusicDiscovery#8]
![screenshot 2017-02-07 16 47 52](https://cloud.githubusercontent.com/assets/16734260/22698599/452b1bda-ed55-11e6-8931-0e0267963aa7.png)

can you limit the search bar width? on desktop it looks really large.

**Comment by fplacardona** [comment]
<img width="1280" alt="screen shot 2017-02-07 at 17 12 33" src="https://cloud.githubusercontent.com/assets/19613319/22699734/a72211ec-ed58-11e6-93c5-ca8d1fc46349.png">

This is how it looks like in Firefox, where I was programming and testing

**Comment by lanzwerk** [comment]
is there a way to limit it for chrome? i think diepold is using it :)
safari has the right width but an imperfection around the corners of the magnifying glass 
<img width="397" alt="screenshot 2017-02-07 17 15 26" src="https://cloud.githubusercontent.com/assets/16734260/22699910/1cf10374-ed59-11e6-9213-95717d8b979c.png">

**Comment by fplacardona** [comment]
<img width="1280" alt="screen shot 2017-02-07 at 17 18 46" src="https://cloud.githubusercontent.com/assets/19613319/22700047/8ef018d4-ed59-11e6-9a79-5082b58f98e5.png">

Can't do much, this is how it looks like for me in Chrome

**Comment by fplacardona** [comment]
Corrected the imperfection  around the corners, will commit now
